api_dictionary_list:
    path: /api/dictionaries
    controller: App\Controller\DictionaryController::index
    methods: GET
api_dictionary_create:
    path: /api/dictionaries
    controller: App\Controller\DictionaryController::create
    methods: POST
api_dictionary_show:
    path: /api/dictionaries/{id}
    controller: App\Controller\DictionaryController::show
    methods: GET
index:
    path: /{any}
    controller: App\Controller\DefaultController::index
    requirements:
        any: .*
    defaults:
        any: null
